### ISSUE TITLE
The plugin is incompatible with the latest beta release of Zotero

### ISSUE THREAD

**Issue by dualer** [egh/zotxt#31]
see [this](https://github.com/ethanwillis/zotero-scihub/issues/67)

**Comment by egh** [comment]
Looking into it! My tests are failing - trying to work out if this is revealing a bug in zotero or in my code (more likely!)

**Comment by egh** [comment]
https://forums.zotero.org/discussion/94485/possible-zotero-beta-bug-div-getattribute-is-not-a-function#latest

**Comment by dualer** [comment]
> https://forums.zotero.org/discussion/94485/possible-zotero-beta-bug-div-getattribute-is-not-a-function#latest

The developer of Zotero needs you to provide more information on this issue.

**Comment by egh** [comment]
https://groups.google.com/g/zotero-dev/c/2zbm_j9whiQ/m/HZZRxFCkAgAJ

**Comment by egh** [comment]
Should be fixed in https://github.com/egh/zotxt/releases/tag/v6.0.0

**Comment by czerwony-brudnopis** [comment]
I still have the same problem as described above, i.e. "The add-on "zotxt" could not be installed. It may be
incompatible with this version of Zotero."

**Comment by danieltomasz** [comment]
@czerwony-brudnopis  Did you download the right version? Ver 6. work with Zotero 6, for the previous Zotero version (not beta. you need 5.1.4)

**Comment by egh** [comment]
I'm sorry, I'm trying to replicate this but I can't (even using the old version of zotxt on Zotero 6 I am unable to replicate).

**Comment by egh** [comment]
Ah, I did forget to push an update to the automatic updated. Done

**Comment by egh** [comment]
Also I got the version restrictions wrong. For some reason my local Zotero was not enforcing the restrictions. This issue should be corrected now.
